### PR TITLE
control audio noise

### PR DESCRIPTION
**Pull request by smithyj**

### CODE REVIEW

**Comment by smithyj** [comment]
Why not provide users with this option

**Comment by dchest** [comment]
Please see my reply here https://github.com/dchest/captcha/issues/33#issuecomment-679073107

**Comment by smithyj** [comment]
I have read your reply, but is it not good to provide users with their own choices?

**Comment by dchest** [comment]
I’m trying to keep users safe, so in this case, no. You are however free to use your own fork with this feature.

**Comment by smithyj** [comment]
so thank you

**Pull request closed without merging**
