### PR TITLE
add WriteString for outside usage.

### PR DESCRIPTION
**Pull request by bandheight**
E.g., captcha over email or sms.

Signed-off-by: Hosun Zhu <hosun@linux.com>

### CODE REVIEW

**Comment by dchest** [comment]
Sorry, I don't understand what this achieves. This writes captcha solution so that it can be sent over SMS or email? What's the purpose of the captcha then?

Thanks!

**Comment by bandheight** [comment]
1. `GetCpatchaID()`  get cpatcha id from system. this api return `cpatchaId`
2. `SendCpatchatOverEmail(cpatchaId, email)` send cpatcha over email. this step need `WriteString`
3. `Verify(cpatchaId, cpatcha, email)` verify cpatcha

Without WriteString, I would not be able to get the original verification code and email it.

**Comment by dchest** [comment]
This means that you want to _bypass_ captcha by sending the solution by email? I don't think this should be available in this package, since `WriteString` would make people believe that it's safe to give out the solution.

If you still want it, you can do this without any changes to the package:

Initialize a custom memory store:

```go
var myStore = captcha.NewMemoryStore(captcha.CollectNum, captcha.Expiration)
...
captcha.SetCustomStore(myStore)
```

Then use it:

```go
id := captcha.New()

solution := myStore.Get(id, false)
if d == nil {
	return ErrNotFound
}
```

`solution` is now the string you need.

**Comment by bandheight** [comment]
It ’s not bypassed, it ’s just another way to display the verification code.
Your code work. BUT I think we should provide a high-level API to allow users to customize how to display verification code.

**Comment by dchest** [comment]
You shouldn't use this package to verify email addresses, use a proper verification system (generate two random 16-byte values: identifier and verifier, put them into the database, then concatenate them into a token, put into the link and send to user. When the user clicks on the link, split the token to identifier and verifier, lookup the database record by identifier and compare the verifier -- if it matches, the email is verified.)

This package focuses on captcha — an image or an audio that is hard for computers to read, but easy for humans. The rest is outside of its scope.

**Pull request closed without merging**
