### PR TITLE
update readme for skew value

### PR DESCRIPTION
**Pull request by lcp0578**
If your captcha is difficult to identify, please turn it down.example 0.9 => 0.1

### CODE REVIEW

**Comment by dchest** [comment]
Thanks, but this should be either configurable by user or not mentioned at all, since it's a package-internal variable.

**Comment by lcp0578** [comment]
Oh, it real is package-internal variable, but I hope is it configurable.
This may add an additional explanation, I have been puzzled for a long time.
I can't enter its value correctly, when he is 0.9.

**Comment by dchest** [comment]
Maybe the image is too small? 

Anyway, indeed, this should be configurable, but currently there's no mechanism for that apart from editing code.

**Comment by lcp0578** [comment]
Thank you, I am a go beginner, thank you for writing such excellent package,.
I hope to add a set func.

**Pull request closed without merging**
